# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 2
    gaps_out = 4
    border_size = 1

    # Change to niri-like side-scrolling layout
    # layout = scrolling
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8

    # Window opacity (1.0 = opaque, 0.0 = fully transparent)
    active_opacity = 1.0
    inactive_opacity = 0.85

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    # dim_inactive = true
    # dim_strength = 0.15

    blur {
        size = 3
        passes = 2
    }
}

# Disable transparency and blur for scratchpad windows to avoid layered rendering overhead
windowrule = match:class Alacritty, opacity 0.9 override 0.82 override
windowrule = opacity 1.0 override 1.0 override, match:workspace special:magic
windowrule = no_blur on, match:workspace special:magic

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    # Disable all animations
    # enabled = no
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
